### ISSUE TITLE
同步失败后重试

### ISSUE THREAD

**Issue by gaoyifan** [knight42/Yuki#5]
从状态页面来看，同步失败的频率还是蛮高的。许多情况下，可以依靠重试来提供成功率。

建议当发生同步错误后，判断返回值，如果错误原因是网络故障、文件消失（rsync 24）类型的错误，就重试1~2次。

这部分的功能可以考虑增加到ustcmirror/base的框架中。在ustcmirror/rsync（或类似）镜像中定义重试次数、返回值范围，base在同步完成后执行相关逻辑。

**Comment by knight42** [comment]
现在默认不会重试。如果有个别源同步失败的频率比较高的话，可以通过 `yuki repo update $repo retry=$count` 设置重试次数。

**Comment by gaoyifan** [comment]
赞！ ubuntu-old-release 经常性被reset，于是我给xtom的机器配置了30次重试🙈

**Comment by knight42** [comment]
@gaoyifan xtom 上还没部署新的 yuki...

**Comment by gaoyifan** [comment]
@knight42 唔.... 但 retry 似乎能正常工作
