### ISSUE TITLE
同一个仓库启动多个post_sync.sh脚本

### ISSUE THREAD

**Issue by gaoyifan** [knight42/Yuki#8]
例如pypi：
由于pypi文件比较多，上次`post_sync.sh`还没运行完，新的同步就开始了。
<img width="823" alt="screen shot 2017-08-20 at 10 15 26" src="https://user-images.githubusercontent.com/5450996/29491535-09456a42-8591-11e7-8e57-ab52bd9c0632.png">

希望在上次`post_sync.sh`未执行完成时，忽略新的同步。

**Comment by knight42** [comment]
感觉这个功能不太好做。。如果改为对同一个 repo 只能有一个 `post_sync.sh` 在运行怎么样呢？

**Comment by gaoyifan** [comment]
“同一个 repo 只能有一个 `post_sync.sh` 在运行” 有两种逻辑：
1. 触发`post_sync.sh`前检查是否已经有同repo的`post_sync.sh`在运行。如果有，就不执行新的`post_sync.sh`。
2. 1. 触发`post_sync.sh`前检查是否已经有同repo的`post_sync.sh`在运行。如果有，就杀掉旧的`post_sync.sh`，然后启动一个新的`post_sync.sh`。

如果是第一种逻辑，可能导致repo与repo-attrs不一致。 第二种应该没什么问题。

**Comment by knight42** [comment]
@gaoyifan 如果是第二种的话，会不会存在运行时间过长导致一直未能完整执行的情况？第一种的话，不一致会导致什么问题呢？

**Comment by gaoyifan** [comment]
## 第一种逻辑

遇到以下两种状态之一：
1. 第二次更新的文件内容是已经被第一次post_sync.sh同步过的目录
2. 第二次更新中删除了一部分文件

由于第二次post_sync.sh被取消了，这些修改可能不会同步到repo-attrs。导致下游在同步时遇到同步错误（一般是file vanished）

## 第二种逻辑

如果遇到时间过长，一直未完整同步，那么应该降低同步频率，或者改善磁盘的繁忙状态，而不是强行设置很高的同步频率。（此处可以有监控，如果检测到post_sync.sh被连续kill 3次，则给alert@ustclug.org发信报警）

**Comment by knight42** [comment]
现在我改了一下 `post_sync.sh`，执行命令前会杀掉旧的 `post_sync.sh`。
监控连续被 kill 感觉单纯用 bash 不太好做，我先放下了。

**Comment by knight42** [comment]
这个交给 `post_sync.sh` 自行处理吧，先 close 了。
