### ISSUE TITLE
repo-rm删除的仓库仍然会出现在meta-ls中

### ISSUE THREAD

**Issue by gaoyifan** [knight42/Yuki#9]
使用`yuki repo-rm`删除的仓库，仍然会出现在`yuki meta-ls`的结果中。

`repo-rm`没有删干净？

**Comment by knight42** [comment]
这两种信息是存在不同的 collection 里的。`repo-rm` 目前只保证不会再对这个源进行同步，但 meta 信息还留着。

**Comment by gaoyifan** [comment]
能提供一个子命令删除meta数据吗？

**Comment by knight42** [comment]
@gaoyifan  现在应该会删掉相应的 meta 了。你原来要删掉哪些数据，我现在手工帮你删一下吧。

**Comment by gaoyifan** [comment]
多谢！

- [ ] cloudera-cdh5
- [ ] cloudera-cm5
- [ ] cloudera-kafka

**Comment by knight42** [comment]
@gaoyifan done
